# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
env:
  - DJANGO_VERSION=1.10.1

# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# Команда для запуска тестов, в моем случае они запускаются именно так
script: nosetests