# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('airlines', '0001_initial'),
        ('consumers', '0001_initial'),
        ('touroperators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('startDate', models.DateTimeField()),
                ('finDate', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.Airline')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.Booking')),
                ('departureCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Hotel')),
                ('tourOperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touroperators.TourOperator')),
            ],
        ),
    ]
