# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='booking',
        ),
    ]
