# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20161021_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/tours', verbose_name='Изображение тура'),
        ),
    ]
