# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20161021_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
