# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='destination',
            new_name='hotel',
        ),
    ]
