# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20161002_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='departureCity',
            new_name='departure_city',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='finDate',
            new_name='fin_date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tourOperator',
            new_name='tour_operator',
        ),
    ]
