# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20161003_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
