# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20161021_1637'),
        ('tours', '0004_auto_20161023_0033'),
    ]

    operations = [
    ]
