# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20161008_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, height_field='180px', help_text='150x150px', upload_to='images/tours/', verbose_name='Изображение тура', width_field='200px'),
        ),
    ]
