# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='NameAir',
            new_name='name',
        ),
    ]
