# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_booking_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='finDate',
            new_name='fin_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.Consumer'),
        ),
    ]
