# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import current_user


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20161021_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='consumer',
            field=models.ForeignKey(default=current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
