# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_auto_20161003_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='password',
            field=models.CharField(default='', max_length=11),
        ),
    ]
