# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_buying_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
